CREATE database PROJECT;
USE PROJECT;

-- DATA CLEANING

SELECT * FROM HR;

-- CHANGE THE COLUMN NAME

ALTER TABLE HR
CHANGE COLUMN ï»؟id EMP_ID VARCHAR(20) NULL;

-- CHECK DATA 

DESCRIBE HR;

-- CHANGE BIRTH_DATE FORMAT 

UPDATE HR SET BIRTHDATE = CASE 
                          WHEN BIRTHDATE LIKE '%/%' THEN DATE_FORMAT(str_to_date(BIRTHDATE, '%m/%d/%Y'), '%Y-%m-%d')
                          WHEN BIRTHDATE LIKE '%-%' THEN DATE_FORMAT(str_to_date(BIRTHDATE, '%m-%d-%Y'), '%Y-%m-%d')
                          else null
                          end;

ALTER TABLE HR 
MODIFY COLUMN BIRTHDATE DATE;                          
                          
-- CHECK EVERYTHING IS OK                          

SELECT BIRTHDATE FROM HR  ;
SELECT * FROM HR  ;

-- CHANGE HIRE_DATE FORMAT 

UPDATE HR SET HIRE_DATE = CASE 
                          WHEN HIRE_DATE LIKE '%/%' THEN DATE_FORMAT(str_to_date(HIRE_DATE, '%m/%d/%Y'), '%Y-%m-%d')
                          WHEN HIRE_DATE LIKE '%-%' THEN DATE_FORMAT(str_to_date(HIRE_DATE, '%m-%d-%Y'), '%Y-%m-%d')
                          else null
                          end;
                          
ALTER TABLE HR 
MODIFY COLUMN HIRE_DATE DATE;                          
                          
                          
-- CHECK EVERYTHING IS OK                          

SELECT HIRE_DATE FROM HR  ;
SELECT * FROM HR  ;


-- CHECK THE GENDER

SELECT DISTINCT GENDER FROM HR;
-- GENDER IS OK

-- CHECK DATA 

DESCRIBE HR;
SELECT * FROM HR  ;

-- CHANGE TERMDATE FORMAT

UPDATE HR 
SET TERMDATE = DATE(STR_TO_DATE(TERMDATE, '%Y-%m-%d %H:%i:%s'))
WHERE TERMDATE IS NOT NULL AND TERMDATE != '';

ALTER TABLE HR 
MODIFY COLUMN TERMDATE DATE;


-- CHECK EVERYTHING IS OK                          

SELECT TERMDATE FROM HR  ;
SELECT * FROM HR  ;

-- CHECK DATA 

DESCRIBE HR;
SELECT * FROM HR  ;

-- ADD AGE COLUMN

ALTER TABLE HR ADD COLUMN AGE INT;
SELECT * FROM HR  ;

-- ADD DATA TO AGE 

UPDATE HR SET AGE = TIMESTAMPDIFF(YEAR, BIRTHDATE, CURDATE());

-- TIMESTAMPDIFF(): FUNCTION FOR CALCULATE THE DIFF BETWEEN TOW DATES
-- YEAR: Specifies the unit of difference to return
-- BIRTHDATE: The starting date
-- CURDATE(): THE CURRENT DATE   


-- CHECK DATA 

SELECT AGE FROM HR  ;
SELECT * FROM HR  ;

-- CHECK DATA

SELECT MAX(AGE) AS OLDEST , MIN(AGE) AS YOUNGEST FROM HR  ;
SELECT * FROM HR  ;

-- THERE IS A PROBLEM WITH YOUNGEST WE HAVE A NEGATIVE VALUE 

UPDATE HR SET AGE = ABS(AGE);

-- CHECK DATA

SELECT MAX(AGE) AS OLDEST , MIN(AGE) AS YOUNGEST FROM HR  ;
SELECT * FROM HR  ;

-- WE SOLVED THE PROBLEM

-- ANALYSIS PHASE

-- QUESTIONS

-- 1- WHAT IS THE GENDER BREAKDOWN OF EMP IN THE COMPANY ?

	SELECT GENDER, COUNT(*) AS COUNT FROM HR WHERE AGE >= 18 AND TERMDATE IS NULL GROUP BY GENDER;

-- 2- WHAT IS THE RACE/ETHNICITY BRREAKDOWN OF EMP IN THE COMPANY ?

    SELECT RACE, COUNT(*) AS COUNT FROM HR WHERE AGE >= 18 AND TERMDATE IS NULL GROUP BY RACE;

-- 3- WHAT IS THE AGE DISTRIBUTION OF EMP IN THE COMPANY?

    SELECT MAX(AGE) AS OLDEST , MIN(AGE) AS YOUNGEST FROM HR WHERE AGE >= 18 AND TERMDATE IS NULL;
    
    SELECT CASE 
		   WHEN AGE >= 18 AND AGE <= 24 THEN '18-24'
           WHEN AGE >= 25 AND AGE <= 34 THEN '25-34'
           WHEN AGE >= 35 AND AGE <= 44 THEN '35-44'
           WHEN AGE >= 45 AND AGE <= 54 THEN '45-54'
           WHEN AGE >= 55 AND AGE <= 64 THEN '55-64'
           ELSE '65+'
           END AS AGE_GAP, GENDER , COUNT(*) AS COUNT FROM HR WHERE AGE >=18 AND TERMDATE IS NULL GROUP BY AGE_GAP,GENDER ORDER BY 1, 2 ASC ;

-- 4- HOW MANY EMPLOYEES WORK AT HEADQUARTERS VERSUS REMOTE LOCATION ?

   SELECT * FROM HR  ;
   SELECT LOCATION , COUNT(*) AS COUNT FROM HR WHERE AGE >=18 AND TERMDATE IS NULL GROUP BY LOCATION ORDER BY 1 ;
   
-- 5- WAHT IS THE AVERAGE LENGHT OF EMPLOYMENT FRO EMPLOYEES WHO HAVE BEEN TERMINATED ? \
   
   SELECT * FROM HR;
   SELECT ROUND(AVG(DATEDIFF(TERMDATE, HIRE_DATE))/365,0) AS AVERAGE FROM HR WHERE  TERMDATE <= CURDATE() AND TERMDATE  IS NOT NULL AND AGE >=18;
   
 -- 6- HOW DOES THE GENDER DISTRIBUTION VARY ACROSS DEPARTMENTS AND JOB TITLE ?  
 
    SELECT * FROM HR;
    SELECT DEPARTMENT, GENDER , COUNT(*) AS COUNT FROM HR WHERE AGE >=18 AND TERMDATE IS NULL GROUP BY GENDER, DEPARTMENT ORDER BY 1 ;  
    
 -- 7- WHAT IS THE DISTRIBUATION OF JOB TITLE ACROSS THE COMPANY ? 
    
    SELECT * FROM HR;
    SELECT JOBTITLE , COUNT(*) AS COUNT FROM HR  WHERE AGE >=18 AND TERMDATE IS NULL GROUP BY JOBTITLE  ORDER BY JOBTITLE DESC ;
  
  -- 8- WHICH DEPARTMENT HAS THE HIGHEST TURNOVER RATE  ?
	
     SELECT * FROM HR; 
     SELECT DEPARTMENT, TOTAL_COUNT, TERMINATED_COUNT, TERMINATED_COUNT/TOTAL_COUNT AS TERMINATION_RATE
	 FROM ( SELECT DEPARTMENT, COUNT(*) AS TOTAL_COUNT, SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END) AS TERMINATED_COUNT
     FROM HR WHERE AGE >=18 GROUP BY DEPARTMENT) AS SUBQUERY ORDER BY TERMINATION_RATE DESC ; -- IMPORTANT QUERY
     
 -- 9- WHAT IS THE DISTRIBUTION OF EMPLOYEES ACROSS LOCATION BY CITY AND STATE  ? 
 
    SELECT * FROM HR;
    SELECT  LOCATION_STATE, COUNT(*) AS COUNT FROM HR WHERE AGE >=18 AND TERMDATE IS NULL GROUP BY  LOCATION_STATE ORDER BY COUNT DESC ;
    
 -- 10- HOW HAS THE COMPANYS EMP COUNT CHANGED OVER TIME BASED ON HIRE AND TERM DATE  ?
 
    SELECT * FROM HR;
    SELECT YEAR, HIRES, TERMINATIONS, HIRES - TERMINATIONS AS CHANGED_OVER_TIME, ROUND((HIRES - TERMINATIONS)/HIRES * 100 ,2) AS NET_CHANGED_PERCENT
    FROM ( SELECT YEAR(HIRE_DATE) AS YEAR, COUNT(*) AS HIRES, SUM(CASE WHEN TERMDATE IS NOT NULL AND TERMDATE <= CURDATE() THEN 1 ELSE 0 END) AS TERMINATIONS
    FROM HR WHERE AGE >= 18 GROUP BY YEAR(HIRE_DATE)) AS SUBQUERY ORDER BY YEAR ASC;
    
-- 11- WHAT IS THE TENURE DISTRIBUTIOAN FOR EACH DEPARTMENT  ?

   SELECT * FROM HR;
   SELECT DEPARTMENT, ROUND(AVG(DATEDIFF(TERMDATE, HIRE_DATE)/365),0) AS AVG_TENURE FROM HR WHERE TERMDATE <= CURDATE()  AND TERMDATE IS NOT NULL AND AGE >= 18 GROUP BY DEPARTMENT  ;
    
    
    
    


   
   
   
   



